config/routes.rb
Rails.application.routes.draw do
  resources :pets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pets#index"
  get "/signup" => "users#new"
  post "/users" => "users#create"
  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :breed, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authenticate_user
    redirect_to "/login", status: :see_other unless current_user
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find_by(id: params[:id])
  end

  def new
    @pet = Pet.new
    render template: "pets/new"
  end

  def create
    @pet = Pet.new(pet_params)

    if @pet.save
      redirect_to "/pets/#{@pet.id}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pet = Pet.find_by(id: params[:id])
    render template: "pets/edit"
  end

  def update
    @pet = Pet.find_by(id: params[:id])
    @pet.name = params[:pet][:name] || @pet.name
    @pet.breed = params[:pet][:breed] || @pet.breed
    @pet.image = params[:pet][:image] || @pet.image
    if @pet.save
      redirect_to "/pets/#{@pet.id}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @pet = Pet.find_by(id: params[:id])
    @pet.destroy
    redirect_to "/pets", status: :see_other
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :breed, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render template: "sessions/new"
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/"
    else
      redirect_to "/login"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/login"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render template: "users/new"
  end

  def create
    @user = User.new(
      name: params[:user][:name],
      email: params[:user][:email],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
    )
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with model: @pet do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @pet.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :breed %><br>
    <%= form.text_area :breed %><br>
    <% @pet.errors.full_messages_for(:breed).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

    <div>
    <%= form.label :image %><br>
    <%= form.text_area :image %><br>
    <% @pet.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit <%= @pet.name %>

<%= render "form", pet: @pet %>
<%= link_to "Destroy pet", pet_path(@pet), data: {turbo_method: :delete} %>

app/views/pets/index.html.erb
<h1>All Pets!</h1>
<div class="carousel-item">
<% @pets.each do |pet|%>
  <img src="<%= pet.image %>" alt="...">
  <div class="carousel-caption d-none d-md-block">
    <h2><%= pet.name %></h2>
    <p>Breed: <%= pet.breed %></p>
    <%= link_to pet.name, pet %>
  </div>
<% end %>
</div>

app/views/pets/new.html.erb
<h1>New Pet</h1>
<%= render "form", pet: @pet %>

app/views/pets/show.html.erb
<div class="row">
  <div class="col-3">
  </div>
  <div class="col-3">
    <h1><%= @pet.name %></h1>
    <p>Breed: <%= @pet.breed %></p>
    <a href="/pets">Back to all pets</a>
    <%= link_to "Destroy pet", pet_path(@pet), data: {turbo_method: :delete} %>
  </div>
  <div class="col-3">
    <img src="<%= @pet.image %>">
  </div>
  <div class="col-3">
  </div>
</div>

app/views/users/new.html.erb
<h1>Signup</h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
    <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>>